### ISSUE TITLE
Can it replace the browser's default history shortcut key CTRL+H?

### ISSUE THREAD

**Issue by GEEKCX** [raingart/Better-History#4]
1.Set the shortcut key function?
2.Ctrl+H replaces the browser’s default history function

**Comment by raingart** [comment]
[history-extensions_v1.31.3.zip](https://github.com/user-attachments/files/16922717/history-extensions_v1.31.3.zip)

try the dev ver. I added `Open history page`

![Screenshot from 2024-09-08 18-28-01](https://github.com/user-attachments/assets/6465c07c-1045-4645-aa32-9456418f0e8d)

**Comment by raingart** [comment]
or do you want to open the default `chrome://history/`
then there is no way to do it settings

but if you really need it, remove the lines in `manifest.json`:
```
"chrome_url_overrides": {
    "history": "/html/history.html"
 },
```

extension is stored in `<your-chrome-config-directory>/Default/Extensions/pmolchcgkagchldkgphmlaplgmagldfn/`

**Comment by GEEKCX** [comment]
👍cool!

**Comment by raingart** [comment]
I did a deployment to the store. Once chrome store approved, set the hotkeys
